### ISSUE TITLE
Select w/ Other - Other Option should not show unless "Other" is selected from the dropdown menu.

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/moodle_enrol_survey#10]

**Comment by mjsamberg** [comment]
Moved to staging for testing. Assigning to @adreier and @maday4 for testing.

**Comment by adreier** [comment]
Is this for "Primary Area of Responsibility"? If so, I am not provided with a text field when selecting the "Other" option.

**Comment by mjsamberg** [comment]
No, this is for the Other option in the registration survey.

**Comment by adreier** [comment]
Works in Chrome, Firefox, and Safari for Mac.

**Comment by mjsamberg** [comment]
Moved to production.
